#!/bin/bash
if [ $# -gt 0 ]; then
  # command line input mode
  echo $(date +'[%Y-%m-%m] %H:%M:%S >>') "$*"
else
  # pipe mode
  while :
  do
    if read -t 1 input ; then
      echo $(date +'[%Y-%m-%m] %H:%M:%S >>') "$input"
    fi
  done
fi
